### ISSUE TITLE
Unexpected value of task_data->value within an event callback

### ISSUE THREAD

**Issue by madagra** [OpenMPToolsInterface/LLVM-openmp#39]
Hi guys,

I have been trying to build a small tool to measure thread barrier times using the OMPT interface. I came across an anomalous behavior while trying to retrieve the data associated to a task within an event callback (`task_data` structure).
I implemented a custom callback for the `sync_region_wait` event. When the wait event is in the `ompt_scope_begin` state I set `task_data->value` to a unique integer identifier in the following way:
```
    switch(state)
    {
        case(ompt_scope_begin):
            task_data->value = ompt_get_unique_id_fn();
            printf("[thread %p] sync region start: task %ld\n",thread_data,
                   task_data->value);
            break;
        case(ompt_scope_end):
            printf("[thread %p] sync region end: task %ld\n",thread_data,
                   task_data->value);
            break;
    }
```
I was thinking that the value assigned to the `value` field would have been preserved until the `ompt_scope_end` was reached. This is the case for some of the tasks, but for others this value appears to be reset to 0, i.e. `ompt_data_none`. Notice that if I retrieve the task data pointer using `ompt_get_task_info()` I get the correct value as expected.

A small reproducer of the problem can be found [here](https://github.com/madagra/OMPT-issues/tree/master/task_info_value). Thanks in advance for all help and clarifications.
Best,
Mario

**Comment by jprotze** [comment]
Thank you for bringing up this issue.

I think this should be fixed in 4b29de49. Can you give that a try?

**Comment by madagra** [comment]
Thanks for the quick response. I tried the patch with my reproducer but it is still not working. The symptoms are indeed different: a segmentation fault occurs at the end of the program execution. The `task_data` pointer retrieved using the `ompt_get_task_info()` function seems corrupted.

**Comment by jprotze** [comment]
You are not evaluating the value returned by the function. I think, it should be 0 at that point.
After the runtime entered the final barrier, the implicit task might be poped from the internal data structures at any time. The only safe way to access the data pointer at that time is the argument provided in the barrier-end and implicit-task-end event.

**Comment by madagra** [comment]
Thanks, you are right. The return value of `ompt_get_task_info()` is indeed 0 at the final barrier except for the master thread. I close the issue, my reproducer behaves as expected. 
Just as a suggestion, I think it would be nice to mention in the documentation that the `ompt_get_task_info()` cannot be safely used within event callbacks right before the final barrier. I guess this is implementation specific anyway.
